project:
  type: website
  output-dir: docs


website:
  navbar: true
  page-navigation: true
  title: "MDPIexploreR"
  favicon: images/favicon.ico
  sidebar:
    logo: "images/mdpiexplorer_logo.png"
    pinned: true
    align: center
    tools:
        - icon: twitter
          href: https://twitter.com/pagomba
        - icon: github
          href: https://github.com/pgomba/MDPI_explorer
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Tutorial
      - href: datasets.qmd
        text: Datasets
      - href: changelog.qmd
        text: Changelog
 
  site-url: 'https://pgomba.github.io/MDPI_explorer/'
  site-path: '/'
  open-graph: 
    image: "images/mdpiexplorer_tc.png"
    site-name: "MDPIexploreR"
  twitter-card:
    card-style: summary_large_image
    creator: "@pagomba"
    image: "images/mdpiexplorer_tc.png"
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: visual
      


